# Generated by Django 4.2.4 on 2023-09-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_paymenttable_user_paymenttable_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttable',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.booking'),
        ),
    ]
