# Generated by Django 4.2.4 on 2023-09-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_paymenttable_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentTable',
            new_name='Payment',
        ),
    ]
