# Generated by Django 4.2.4 on 2023-09-01 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_paymenttable_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeToken', models.CharField(max_length=64)),
                ('amount', models.CharField(max_length=16)),
                ('book', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.booking')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
