# Generated by Django 4.2.4 on 2023-09-01 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_stripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripeToken', models.CharField(max_length=64)),
                ('amount', models.CharField(max_length=16)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booking')),
            ],
        ),
    ]
