# Generated by Django 4.2.4 on 2023-09-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_paymenttable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='paid',
        ),
        migrations.DeleteModel(
            name='PaymentTable',
        ),
    ]
