# Generated by Django 4.2.4 on 2023-09-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_booking_paid_delete_paymenttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='reset_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
